name: Backend service CI

on: [push, pull_request]

env:
  MAVEN_ARGS: -B -V -ntp -e -Djansi.passthrough=true -Dstyle.color=always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn $MAVEN_ARGS --batch-mode --update-snapshots verify
        working-directory: ./service
      - name: Docker Login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and Publish Docker Image
        run: cd service ; mvn clean deploy -Ddocker.user=${{ secrets.DOCKERHUB_USERNAME }} -Ddocker.password=${{ secrets.DOCKERHUB_PASSWORD }} -Ddocker.url=hub.docker.com 
        env:
          DOCKER_UPDATE_LATEST: true
